export default {
  CHANGE_EVENT: 'CHANGE_EVENT',

  ActionTypes: {
    TEST_STORE: 'TEST_STORE',
    SHOW_SIDEBAR: 'SHOW_SIDEBAR',
    HIDE_SIDEBAR: 'HIDE_SIDEBAR',
    COUNT_UP: 'COUNT_UP',
    COUNT_DOWN: 'COUNT_DOWN'
  }
};
